### ISSUE TITLE
Crash because of missing file after 3.0 update

### ISSUE THREAD

**Issue by xhs345** [OleVik/grav-plugin-imgcaptions#20]
Just updated to the new experimental version and webpage is no longer opening. Instead seeing error message:

`E_WARNING - include(/home/grav/www/html/user/plugins/imgcaptions/vendor/autoload.php): failed to open stream: No such file or directory`

So it looks like it didn't automatically install all required dependencies

**Comment by xhs345** [comment]
I also don't understand why the plugin is listed under stable releases but after install its tag is shown as test release

**Comment by xhs345** [comment]
Running composer install manually fixed the issue for me.

As a note, got the following warning:

> Deprecation warning: Your package name https://github.com/OleVik/grav-plugin-imgcaptions is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.

**Comment by OleVik** [comment]
I see where the problem lies, I'll have a fix out as soon as possible. It's listed as stable but marked as a test release because of the `testing`-parameter in blueprints.yaml, which I tend to forget to rectify prior to a release.

**Comment by OleVik** [comment]
This should be fixed in [v3.0.1](https://github.com/OleVik/grav-plugin-imgcaptions/releases/tag/v3.0.1),  please test it when you get a chance.

**Comment by xhs345** [comment]
Thanks for the quick response! Installed it (using direct install though the admin panel) and getting another error now when opening my homepage

> [2019-08-12 19:20:57] grav.CRITICAL: Call to a member function url() on null - Trace: #0 /home/grav/www/html/user/plugins/imgcaptions/classes/Markdown.php(152): Grav\Plugin\ImgCaptionsPlugin\API\Source->render('psbe%20copy.jpe...', '/') #1 /home/grav/www/html/user/plugins/imgcaptions/imgcaptions.php(115): Grav\Plugin\ImgCaptionsPlugin\API\Markdown->render('Final post of t...') #2 /home/grav/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Grav\Plugin\ImgCaptionsPlugin->output(Object(RocketTheme\Toolbox\Event\Event), 'onPageContentRa...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #3 /home/grav/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPageContentRa...', Object(RocketTheme\Toolbox\Event\Event)) #4 /home/grav/www/html/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPageContentRa...', Object(RocketTheme\Toolbox\Event\Event)) #5 /home/grav/www/html/system/src/Grav/Common/Grav.php(365): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPageContentRa...', Object(RocketTheme\Toolbox\Event\Event)) #6 /home/grav/www/html/system/src/Grav/Common/Page/Page.php(710): Grav\Common\Grav->fireEvent('onPageContentRa...', Object(RocketTheme\Toolbox\Event\Event)) #7 /home/grav/www/html/vendor/twig/twig/src/Template.php(690): Grav\Common\Page\Page->content() #8 /home/grav/www/html/cache/twig/24/249518d25d59b32bb3ef189e2a6221e54499d9260b2761eca52e51161e369ead.php(161): Twig\Template->getAttribute(Object(Grav\Common\Page\Page), 'content', Array) #9 /home/grav/www/html/vendor/twig/twig/src/Template.php(443): __TwigTemplate_e48cc0dbd8eea52b3ef8a703f4992a93707207d095d77f69986c91f5ac03f041->doDisplay(Array, Array) #10 /home/grav/www/html/vendor/twig/twig/src/Template.php(414): Twig\Template->displayWithErrorHandling(Array, Array) #11 /home/grav/www/html/cache/twig/56/56fe2ad86b7eb49c272b800568c20090edbb5bf1ae99ecbdcf6b4ebde0414167.php(119): Twig\Template->display(Array) #12 /home/grav/www/html/vendor/twig/twig/src/Template.php(216): __TwigTemplate_a2e7631307c7dc98f65344dbd8b541df5d11dfa7087d9de0cc2a68fd4061c6ca->block_content(Array, Array) #13 /home/grav/www/html/cache/twig/c5/c5e64cf5d978810a2825461edda39ba76955c7d6a5ef80c7003f9c085fca2353.php(69): Twig\Template->displayBlock('content', Array, Array) #14 /home/grav/www/html/vendor/twig/twig/src/Template.php(443): __TwigTemplate_ea0585d69a40fd6b94432dd013198b5ea7699ecb7b292e61f6ff5a4dece6fb37->doDisplay(Array, Array) #15 /home/grav/www/html/vendor/twig/twig/src/Template.php(414): Twig\Template->displayWithErrorHandling(Array, Array) #16 /home/grav/www/html/cache/twig/56/56fe2ad86b7eb49c272b800568c20090edbb5bf1ae99ecbdcf6b4ebde0414167.php(39): Twig\Template->display(Array, Array) #17 /home/grav/www/html/vendor/twig/twig/src/Template.php(443): __TwigTemplate_a2e7631307c7dc98f65344dbd8b541df5d11dfa7087d9de0cc2a68fd4061c6ca->doDisplay(Array, Array) #18 /home/grav/www/html/vendor/twig/twig/src/Template.php(414): Twig\Template->displayWithErrorHandling(Array, Array) #19 /home/grav/www/html/vendor/twig/twig/src/Template.php(422): Twig\Template->display(Array) #20 /home/grav/www/html/vendor/twig/twig/src/TemplateWrapper.php(47): Twig\Template->render(Array, Array) #21 /home/grav/www/html/vendor/twig/twig/src/Environment.php(384): Twig\TemplateWrapper->render(Array) #22 /home/grav/www/html/system/src/Grav/Common/Twig/Twig.php(388): Twig\Environment->render('modular.html.tw...', Array) #23 /home/grav/www/html/system/src/Grav/Common/Service/OutputServiceProvider.php(28): Grav\Common\Twig\Twig->processSite('html') #24 /home/grav/www/html/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #25 /home/grav/www/html/system/src/Grav/Common/Processors/RenderProcessor.php(28): Pimple\Container->offsetGet('output') #26 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\RenderProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #27 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #28 /home/grav/www/html/system/src/Grav/Common/Processors/DebuggerAssetsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #29 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\DebuggerAssetsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #30 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #31 /home/grav/www/html/system/src/Grav/Common/Processors/PagesProcessor.php(69): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #32 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PagesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #33 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #34 /home/grav/www/html/system/src/Grav/Common/Processors/TwigProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #35 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TwigProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #36 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #37 /home/grav/www/html/system/src/Grav/Common/Processors/AssetsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #38 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\AssetsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #39 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #40 /home/grav/www/html/system/src/Grav/Common/Processors/SchedulerProcessor.php(29): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #41 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\SchedulerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #42 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #43 /home/grav/www/html/system/src/Grav/Common/Processors/BackupsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #44 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\BackupsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #45 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #46 /home/grav/www/html/system/src/Grav/Common/Processors/TasksProcessor.php(59): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #47 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TasksProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #48 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #49 /home/grav/www/html/system/src/Grav/Common/Processors/RequestProcessor.php(52): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #50 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\RequestProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #51 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #52 /home/grav/www/html/system/src/Grav/Common/Processors/ThemesProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #53 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ThemesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #54 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #55 /home/grav/www/html/system/src/Grav/Common/Processors/PluginsProcessor.php(30): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #56 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PluginsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #57 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #58 /home/grav/www/html/system/src/Grav/Common/Processors/InitializeProcessor.php(78): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #59 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\InitializeProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #60 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #61 /home/grav/www/html/system/src/Grav/Common/Processors/DebuggerProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #62 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\DebuggerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #63 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #64 /home/grav/www/html/system/src/Grav/Common/Processors/ErrorsProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #65 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ErrorsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #66 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #67 /home/grav/www/html/system/src/Grav/Common/Processors/LoggerProcessor.php(48): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #68 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\LoggerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #69 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #70 /home/grav/www/html/system/src/Grav/Common/Processors/ConfigurationProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #71 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ConfigurationProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #72 /home/grav/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #73 /home/grav/www/html/system/src/Grav/Common/Grav.php(249): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #74 /home/grav/www/html/index.php(53): Grav\Common\Grav->process() #75 {main} [] []

**Comment by OleVik** [comment]
Could you share some of the Markdown you are using to set images with? I think my tests may have not covered enough cases.

**Comment by xhs345** [comment]
Pretty sure it's because of spaces in the filename which get transformed into %20 in markdown for me.

E.g.
`![family tree](psbe-2%20copy.jpeg)`
and
`![family sitting](psb%20%281%29.jpeg)`

**Comment by OleVik** [comment]
That is the correct behavior for getting images with spaces in the name when rendering, as it makes it a valid URL, but it's not something that should be in Markdown. Is the plugin causing that transformation? It only affects the rendering of HTML or Markdown on run-time, not stored files.

**Comment by xhs345** [comment]
Transformation happens automatically when inserting an image to a post using the admin plugin ui.

**Comment by OleVik** [comment]
I just committed a few changes to master that should cover path resolution better. The following has been tested and works:

```markdown
![Figure 18](fig18.jpg "Figure 18")

![Sherlock](learn/book Cover.jpg "Sherlock")

![Allgemeine](/article/allgemeine-erdbeschreibung.jpg "Allgemeine")

![Cochinchine](../article/la-cochinchine-francaise-en-1878-par-le-comite-agricole-et-industriel-de-la-cochinchine.jpg "Cochinchine")

![George and Napoleon](article/george-iii-and-bonaparte.jpg "George and Napoleon")
```

But streams, like `![Info](user://pages/04.learn/07.cli-console/04.grav-cli-gpm/info.jpg "Info")` do not, currently.

That is a bit of an odd behavior from Admin, and not related to ImgCaptions. ImgCaptions does not hook into Admin at all, other than registering blueprint-options, and contains no JavaScript. Is this a problem that specifically started with and persists after the update to v3.0.0 of this plugin, or did it coincide with an upgrade of Admin as well? Does disabling ImgCaptions yield expected behavior?

**Comment by xhs345** [comment]
Having the filename reference show up with %20 instead of a space was always the case, not sure if it's just because of Admin or related to some other plugin/theme indirectly (not imgcaptions though, tested when disabling the plugin)
So the %20 was always in the name, it's just that imgcaptions started throwing exceptions in v3.

Tried installing master, but still same issue. I'll try to do some debugging as well later

**Comment by X-Ryl669** [comment]
Nope, it still does not work even with your last changes, failing here: `Call to a member function url() on null`

```
            return [
 => Here               'src' => $media->get($source)->url() ?? null,
                'filename' => $source ?? null,
                'page' => $this->page
```
It used to work with 3.0.0 followed by `composer update`.
For what it's worth, here's the value for the variables:
`$source = string(22) "PointDeRose%CC%81e.png"`

Fixed by:
```
            return [
               'src' => $media->get(urldecode($source))->url() ?? null,
                'filename' => $source ?? null,
                'page' => $this->page
```

**Comment by OleVik** [comment]
What is the real name of the file on the disk?

**Comment by OleVik** [comment]
I pushed 3.0.2 to better fall back when path resolution fails. I can add in an `urldecode()`, which will resolve odd encoding in Markdown - though I'd still like to know why that occurs.

**Comment by X-Ryl669** [comment]
> What is the real name of the file on the disk?
`PointDeRosée.png` I think.

**Comment by X-Ryl669** [comment]
Seems to work with last `Source.php`. I'm waiting for the official update to show up. 
Thanks.

**Comment by OleVik** [comment]
v3.0.3 improves handling of encoded characters, but I cannot guarantee that files that do not conform to a pattern of only alphanumericals, dashes, underlines, and dots will work as expected.

**Comment by xhs345** [comment]
My issue is fixed with v3.0.3 
Thanks!
